
services:
  app:
    container_name: "angular-app"
    build:
      context: angular-material
      dockerfile: .docker/Dockerfile
    ports:
      - "4201:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.app.rule=PathPrefix(`/`)"
    #   - "traefik.http.routers.app.entrypoints=web"
    #   - "traefik.http.services.app.loadbalancer.server.port=4200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4200/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bridge


  api:
    container_name: "fastapi-auth"
    build:
      context: backend/fastapi-auth
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi-auth.rule=PathPrefix(`/restapi`)" # Route /restapi requests to this service
      - "traefik.http.routers.fastapi-auth.entrypoints=web"
      - "traefik.http.services.fastapi-auth.loadbalancer.server.port=80"
      - "traefik.http.middlewares.fastapi-auth-stripprefix.stripprefix.prefixes=/restapi"
      - "traefik.http.routers.fastapi-auth.middlewares=fastapi-auth-stripprefix@docker"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bridge

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --api.insecure=true # Enable the Traefik dashboard (for development only)
      - --providers.docker=true # Enable Docker provider
      - --providers.docker.exposedbydefault=true
      - --entrypoints.web.address=:8888 # Define an entry point for HTTP
    ports:
      - "8888:8888"       # Expose HTTP port
      - "8080:8080"   # Expose Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Allow Traefik to listen to Docker events
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.traefik.rule=Host(`localhost`)"
    #   - "traefik.http.routers.traefik.service=api@internal"
    #   - "traefik.http.routers.traefik.entrypoints=web"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
