
services:
  fastapi-poetry-starter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    networks:
      - bridge
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  bridge:
    driver: bridge
