apiVersion: v1
kind: Service
metadata:
  name: fastapi-poetry-starter
spec:
  selector:
    app: fastapi-poetry-starter
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-poetry-starter
spec:
  selector:
    matchLabels:
      app: fastapi-poetry-starter
  replicas: 4
  template:
    metadata:
      labels:
        app: fastapi-poetry-starter
    spec:
      containers:
      - name: fastapi-poetry-starter
        image: fastapi-poetry-starter:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
